### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by MRVDOG** [Tenpi/youtube.ts#1]
Yo,

can you uppercase `youtube.js` to `Youtube.js` and `youtube.d.ts` to `Youtube.d.ts` in the package.json for `main` and `types`... As the files are Uppercased, it causes the module to not be found

thanks

**Comment by Moebytes** [comment]
Hey, the capitalization should not matter. Please uninstall and reinstall the package, if the problem persists post the full error that you are getting

**Comment by Moebytes** [comment]
Actually, I was on an older version of node. Please update to the latest version, I fixed this :)
