### ISSUE TITLE
An import path cannot end with a '.ts' extension.

### ISSUE THREAD

**Issue by timotius02** [Tenpi/youtube.ts#21]
Getting this error in my build when trying out the library. Probably due to the .ts ending in the name of the library. 

Currently using the default Typescript environment setup w/ Remix.

**Comment by Moebytes** [comment]
You need to set moduleResolution to node in`tsconfig.json`, otherwise it thinks you are importing a local file named youtube.ts. Having ".ts" extension in module names is allowed and I've never had issues with it. 

```json
{
    "compilerOptions": {
      "moduleResolution": "node"
    }
}
```

**Comment by timotius02** [comment]
I already had module resolution to node. This is my exact tsconfig. 

```
{
  "include": ["remix.env.d.ts", "**/*.ts", "**/*.tsx"],
  "compilerOptions": {
    "lib": ["DOM", "DOM.Iterable", "ES2019"],
    "isolatedModules": true,
    "esModuleInterop": true,
    "jsx": "react-jsx",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "target": "ES2019",
    "strict": true,
    "baseUrl": ".",
    "paths": {
      "~/*": ["./app/*"]
    },

    // Remix takes care of building everything in `remix build`.
    "noEmit": true
  }
}
```

**Comment by Moebytes** [comment]
Then the error is being generated by your linter, not the typescript compiler. You need to find any rules that say "no import with .ts extension" in your linter config and disable it.

**Comment by timotius02** [comment]
It seem like it is not a linting issue. I've tried ignoring the line and disabling my whole linter but it is still erroring. The only way to get it to not error is to use `@ts-ignore` but that makes the library lose all of its typings.

**Comment by timotius02** [comment]
It seem like it is not a linting issue. I've tried ignoring the line and disabling my whole linter but it is still erroring. The only way to get it to not error is to use @ts-ignore but that makes the library lose all of its typings.  Update: I'm able to use [Moq.ts](https://github.com/dvabuzyarov/moq.ts) perfectly fine, but not this library.

**Comment by Moebytes** [comment]
Using @ts-ignore should not make it lose all of its typings. At least, this is not what should happen in Visual Studio Code. It might be different in other IDE's because displaying the typings is an IDE feature. I suspect that the error you're having is also an IDE error if it is not the ts compiler or linter. I would try switching over to VS Code. 
<img width="360" alt="Screen Shot 2022-04-06 at 1 52 13 PM" src="https://user-images.githubusercontent.com/37512637/162037934-76e37dcc-c3b4-4550-916b-35d5dbdc33a8.png">

**Comment by timotius02** [comment]
I am also already using VS Code, and yes they do disappear. 

![vscode](https://user-images.githubusercontent.com/5110237/162049421-f4ec0839-d3c9-48ec-a27b-0da7a28c5d41.png)

**Comment by Moebytes** [comment]
I hate stating the obvious, but you need to reinstall because all your issues sound like you don't have it installed. 
```
npm uninstall youtube.ts
npm install youtube.ts
```
Also, does this issue occur on a vanilla typescript project (no frameworks like Remix). If it doesn't, you know that it's because of some compiler/linter config set by Remix that you have to change.

**Comment by codetheweb** [comment]
I'm running into [the same issue](https://github.com/codetheweb/muse/runs/5859364065?check_suite_focus=true) with a fairly vanilla Typescript config:
```tsconfig.json
{
  "compilerOptions": {
    "lib": ["ES2019", "DOM"],
    "target": "es2018",
    "module": "ES2020",
    "moduleResolution": "node",
    "declaration": true,
    "strict": true,
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "sourceMap": true,
    "resolveJsonModule": true,
    "noEmit": true
  },
  "include": ["src"],
  "exclude": ["node_modules"]
}
```

`yarn tsc`:

```
Error: src/services/third-party.ts(3,21): error TS2691: An import path cannot end with a '.ts' extension. Consider importing 'youtube.js' instead.
Error: src/services/youtube-api.ts(5,58): error TS2691: An import path cannot end with a '.ts' extension. Consider importing 'youtube.js' instead.
```

**Comment by Moebytes** [comment]
Okay, I renamed the file `Youtube.ts` to `youtube.ts` which should fix an issue on case-sensitive file systems, update to `v0.2.8`.

**Comment by codetheweb** [comment]
Thanks!
