### ISSUE TITLE
This expression is not constructable.

### ISSUE THREAD

**Issue by udaygajavalli** [Tenpi/youtube.ts#8]
error TS2351: This expression is not constructable.
  Type 'typeof import("C:/Users/udayg/Desktop/masterboard-app/node_modules/youtube.ts/dist/youtube")' has no construct signatures.

23     const youtube = new Youtube(environment.googleAPI_KEY);
                           ~~~~~~~

![image](https://user-images.githubusercontent.com/37218552/116227038-4f638f80-a771-11eb-950e-b846fc205a42.png)

**Comment by Moebytes** [comment]
Being imported wrongly. 
```ts
import Youtube from "youtube.ts"
```

**Comment by udaygajavalli** [comment]
![image](https://user-images.githubusercontent.com/37218552/116236358-986d1100-a77c-11eb-8a6f-09b97f66c353.png)
Warning: ./node_modules/sax/lib/sax.js
Module not found: Error: Can't resolve 'stream' in 'C:\Users\udayg\youtube-demo\node_modules\sax\lib'

Warning: C:\Users\udayg\youtube-demo\src\app\app.component.ts depends on 'youtube.ts'. CommonJS or AMD dependencies can cause optimization 
bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies



Error: ./node_modules/youtube.ts/dist/entities/Util.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\udayg\youtube-demo\node_modules\youtube.ts\dist\entities'

Error: ./node_modules/miniget/dist/index.js
Module not found: Error: Can't resolve 'http' in 'C:\Users\udayg\youtube-demo\node_modules\miniget\dist'

Error: ./node_modules/miniget/dist/index.js
Module not found: Error: Can't resolve 'https' in 'C:\Users\udayg\youtube-demo\node_modules\miniget\dist'

Error: ./node_modules/youtube.ts/dist/entities/Util.js
Module not found: Error: Can't resolve 'path' in 'C:\Users\udayg\youtube-demo\node_modules\youtube.ts\dist\entities'

Error: ./node_modules/m3u8stream/dist/index.js
Module not found: Error: Can't resolve 'stream' in 'C:\Users\udayg\youtube-demo\node_modules\m3u8stream\dist'

Error: ./node_modules/m3u8stream/dist/m3u8-parser.js
Module not found: Error: Can't resolve 'stream' in 'C:\Users\udayg\youtube-demo\node_modules\m3u8stream\dist'

Error: ./node_modules/m3u8stream/dist/dash-mpd-parser.js
Module not found: Error: Can't resolve 'stream' in 'C:\Users\udayg\youtube-demo\node_modules\m3u8stream\dist'

Error: ./node_modules/miniget/dist/index.js
Module not found: Error: Can't resolve 'stream' in 'C:\Users\udayg\youtube-demo\node_modules\miniget\dist'

Error: ./node_modules/ytdl-core/lib/index.js
Module not found: Error: Can't resolve 'stream' in 'C:\Users\udayg\youtube-demo\node_modules\ytdl-core\lib'

Error: ./node_modules/ytdl-core/lib/info.js
Module not found: Error: Can't resolve 'timers' in 'C:\Users\udayg\youtube-demo\node_modules\ytdl-core\lib'

Error: ./node_modules/ytdl-core/lib/cache.js
Module not found: Error: Can't resolve 'timers' in 'C:\Users\udayg\youtube-demo\node_modules\ytdl-core\lib'

**Comment by Moebytes** [comment]
You can only use it server-sided. Node modules are not available in the browser.
